# Generated by Django 6.0 on 2026-02-15 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moc_beauty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moc_beauty.client'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sala',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moc_beauty.empleado'),
        ),
        migrations.AddField(
            model_name='cita',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moc_beauty.sala'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='estado_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='moc_beauty.estadoservicio'),
        ),
        migrations.AddField(
            model_name='sala',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='salas', to='moc_beauty.servicio'),
        ),
        migrations.AddField(
            model_name='servicioestado',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moc_beauty.estadoservicio'),
        ),
        migrations.AddField(
            model_name='servicioestado',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='moc_beauty.servicio'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moc_beauty.client'),
        ),
        migrations.AddField(
            model_name='venta',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moc_beauty.empleado'),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moc_beauty.producto'),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moc_beauty.servicio'),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='moc_beauty.venta'),
        ),
    ]
